# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eivind Alexander Bergem
description: > # this means to ignore newlines until "baseurl:"
  Software developer from Oslo, Norway.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eivindbergem.github.io" # the base hostname & protocol for your site
github_username:  eivindbergem

# Build settings
markdown: kramdown
